baseURL = "/"
languageCode = "en-us"
title = "UPSCGQ"
theme = "gq"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2
