baseURL = "/"
languageCode = "en-us"
title = "UPSCGQ"
theme = "gq"
enableEmoji = true
description = "This is it"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Subscribe"
    url = "/subscribe"
    weight = 2